# https://github.com/marketplace/actions/deploy-to-firebase-hosting

name: Deploy to Firebase Hosting's Live Channel on pushes to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Install dependencies
        run: pnpm install
      - name: Install client scripts' dependencies
        run: cd scripts && pnpm install
      - name: Run ESLint
        run: pnpm eslint --fix src/ --ext .ts,.tsx
      - name: Format code
        run: pnpm prettier --write src/
      - name: Build client scripts
        run: cd scripts && pnpm tsc
      - name: Update version's timestamp
        run: cd scripts && pnpm node build/meta-version-timestamp-update.js
      - name: Build app
        run: pnpm craco build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOVA_A3_IND }}"
          channelId: live
          projectId: nova-a3-ind

      - name: Update version
        run: cd scripts && pnpm node build/meta-version-increment.js

      - name: Auto commit
        uses: EndBug/add-and-commit@v7
